# nixpacks.toml
[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
# Install ALL dependencies from package.json
cmds = [
    "echo 'Installing all dependencies...'",
    "npm install next react react-dom --legacy-peer-deps",
    "npm install @prisma/client @next-auth/prisma-adapter next-auth --legacy-peer-deps",
    "npm install bcryptjs mysql2 lucide-react clsx --legacy-peer-deps",
    "npm install tailwindcss autoprefixer postcss --legacy-peer-deps",
    "npm install typescript @types/node @types/react @types/react-dom @types/bcryptjs --legacy-peer-deps",
    "npm install prisma tsx eslint eslint-config-next --legacy-peer-deps",
    "npm install googleapis csv-parser papaparse date-fns zod --legacy-peer-deps",
    "npm install --legacy-peer-deps",
    "echo 'Checking installations...'",
    "ls -la node_modules | head -20"
]

[phases.build]
cmds = [
    "node scripts/build-debug.js"
]

[start]
cmd = "npm run start:railway"

[variables]
NODE_ENV = "production"
