[phases.setup]
nixPkgs = ["nodejs-18_x", "openssl"]

[phases.install]
cmds = [
  "npm install --force",
  "ls -la",
  "ls -la prisma/",
  "cat prisma/schema.prisma | head -20"
]

[phases.build]
cmds = [
  "echo 'DATABASE_URL for build:' && echo $DATABASE_URL",
  "npx prisma generate || echo 'Prisma generate failed'",
  "ls -la node_modules/.prisma/client || echo 'No prisma client found'",
  "npm run build -- --debug"
]

[start]
cmd = "npm start"