# nixpacks.toml
[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
# Explicitly install all dependencies
cmds = [
    "npm install next react react-dom @prisma/client bcryptjs next-auth --legacy-peer-deps",
    "npm install --legacy-peer-deps"
]

[phases.build]
cmds = [
    "node scripts/setup-env.js",
    "npx prisma generate", 
    "npx next build"
]

[start]
cmd = "npm run start:railway"
