# nixpacks.toml
[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
# Force a clean install
cmds = [
    "rm -rf node_modules package-lock.json",
    "npm cache clean --force",
    "npm install --legacy-peer-deps --verbose"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start:railway"

[variables]
NPM_CONFIG_LOGLEVEL = "verbose"
