# This file forces Railway to use npm install instead of npm ci

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
# Force npm install instead of npm ci
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start:railway"