# railway.toml
[build]
builder = "nixpacks"
buildCommand = "npm ci --legacy-peer-deps && npm run build"

[deploy]
startCommand = "npm run start:railway"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/api/health"
healthcheckTimeout = 60

[variables]
NODE_ENV = "production"