[build]
builder = "nixpacks"
# Don't specify buildCommand - let nixpacks.toml handle it

[deploy]
startCommand = "npm run start:railway"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/api/health"
healthcheckTimeout = 60