[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate"

[deploy]
startCommand = "npx prisma db push && npm run db:seed || true && npm run build && npm start"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/api/health"
healthcheckTimeout = 30

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"