# railway.toml
[build]
builder = "nixpacks"
buildCommand = "node scripts/setup-prisma-env.js && npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "node scripts/setup-prisma-env.js && npx prisma db push && npm start"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/api/health"
healthcheckTimeout = 60

[variables]
NODE_ENV = "production"